name: Release
on:
  workflow_dispatch:
defaults:
  run:
    shell: 'bash'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run compile
      - run: npm run package
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: v1.0.0
          name: 1.0.0
          body_path: CHANGELOG.txt
          files: AWA-Helper-GUI.zip
          token: ${{ github.TOKEN }}
